name: demo_movies_map_profile
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  sqflite:
  path:
  widgets_ui:
    git:
      url: https://github.com/rendondeveloper/WidgetsUi.git
      ref: main
  util_commons:
    git:
      url: https://github.com/rendondeveloper/util_commons.git
      ref: main

  cupertino_icons: ^1.0.2
  riverpod: ^2.5.0
  flutter_riverpod: ^2.4.10
  freezed_annotation: ^2.4.1
  go_router: ^13.2.0
  google_maps_flutter: ^2.5.3
  location: ^5.0.0
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  build_runner: ^2.4.8
  freezed: ^2.4.7

flutter:
  generate: true
  uses-material-design: true
